### ISSUE TITLE
browseVignettes doesn't find the vignettes

### ISSUE THREAD

**Issue by pdbailey0** [ahmademad/wCorr#13]
Not sure what to do here.

**Comment by Huade** [comment]
I am still downloading MiKTex. It seems 1)build the vignettes `devtools::build_vignettes()`, and 2) build and reload this package can resolve this issue. Vignettes are copied to `./inst/doc` folder.

For testing, I have changed line 5-9 of .Rmd files to 
```tex
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{wCorr Formulas} 
  %\VignetteEngine{knitr::rmarkdown} 
  %\VignetteEncoding{UTF-8}
```

and

```tex
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{wCorr Arguments}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
```

**Comment by pdbailey0** [comment]
Thanks! Howard, if you would like, please add yourself as a contributor ("ctb") in the DESCRIPTION file.
