### ISSUE TITLE
ranked pearson weighted corr is not equal to spearman weighted corr?

### ISSUE THREAD

**Issue by jerryfuyu0104** [ahmademad/wCorr#59]
r <- mvtnorm::rmvnorm(1000, sigma = matrix(c(1, -0.5, -0.5,1), nrow = 2, byrow = TRUE))
x <- r[, 1]
y <- r[, 2]
wts <- dplyr::ntile(x, 10)
wCorr::weightedCorr(x, y, weights = wts, method = 'spearman')
[1] -0.4143708
wCorr::weightedCorr(rank(x), rank(y), weights = wts, method = 'spearman')
[1] -0.4143708
wCorr::weightedCorr(rank(x), rank(y), weights = wts, method = 'pearson')
[1] -0.4057212
wCorr::weightedCorr(x, y, method = 'spearman')
[1] -0.446387
wCorr::weightedCorr(rank(x), rank(y), method = 'spearman')
[1] -0.446387
wCorr::weightedCorr(rank(x), rank(y), method = 'pearson')
[1] -0.446387

**Comment by pdbailey0** [comment]
Great question! You're running a partially weighted Spearman there. Try

```
wCorr::weightedCorr(wCorr:::wrank(x, w=wts), wCorr:::wrank(y, w=wts), weights = wts, method = 'Pearson')
```

You didn't set a seed so I can't exactly reproduce your results, but, with my data, I do get the same thing for
```
> wCorr::weightedCorr(wCorr:::wrankFast(x, w=wts), wCorr:::wrankFast(y, w=wts), weights = wts, method = 'Pearson')
# [1] -0.4157579
```
and 
```
> wCorr::weightedCorr(x, y, weights = wts, method = 'spearman')
# [1] -0.4157579
```

If you want to read more about this, check out the _wCorrFormulas_ vignette, including the section  "Formulas for Spearman correlations with and without weights"
